### ISSUE TITLE
PHONE version  - remove blue banner above video (header)

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#48] opened 2022-10-14 06:39 UTC

**Comment by jbelien** [comment] 2022-10-14 06:39
Reference: 

![Image](https://user-images.githubusercontent.com/1150563/195779291-3c4e0da4-25c3-4285-8734-ea737b38516d.png)

**Comment by sidorelauku** [comment] 2022-10-26 14:32
This is caused by the css of the video, `position: absolute`, and only appears on the main page. I think would be resolved by changing it to `position: fixed`.

**Closed** 2022-10-27 17:42 UTC
